In [2]:
import pandas as pd
import numpy as np

# 1. Data Loading and Exploration

## * Read all CSV files into Pandas DataFrames

In [3]:
stores = pd.read_csv('stores.csv')
sales = pd.read_csv('sales.csv')
products = pd.read_csv('products.csv')
inventory = pd.read_csv('inventory.csv')
customers = pd.read_csv('customers.csv')

## * Display the first few rows of each DataFrame

In [4]:
stores.head()

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
0,1,City Center,123 Retail Blvd,New York,NY,10001,Northeast,32500.0,2005-05-20
1,2,Mall of Chicago,456 Shopping Ave,Chicago,IL,60611,Midwest,45000.0,2007-08-15
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10
3,4,Houston Galleria,321 Main St,Houston,Texas,77002,Southwest,NaN,2008-11-05
4,5,Phoenix Outlet,654 Desert Rd,Phoenix,AZ,85001,Southwest,18500.0,2010-06-30

In [69]:
sales.head()

,sale_id,date,store_id,customer_id,product_id,quantity,total,payment_method
0,1,2022-01-15,3.0,12,5,2,49.98,Credit Card
1,2,2022-01-16,1.0,5,10,1,49.99,credit card
2,3,2022-01-18,2.0,8,3,1,349.99,DEBIT CARD
3,4,2022-01-20,4.0,20,7,1,349.99,Cash
4,5,2022-01-22,5.0,3,15,1,1599.99,CC

In [70]:
products.head()

,product_id,product_name,category,subcategory,brand,price,cost,weight
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
2,3,Sony WH-1000XM4,ELECTRONICS,Headphones,Sony,349.99,210.00,0.60
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
4,5,Nike Classic Tee,Clothing,Shirts,Nike,24.99,12.50,0.20

In [71]:
inventory.head()

,inventory_id,store_id,product_id,quantity_in_stock,last_restock_date,reorder_level
0,1,1,1,25,2022-10-15,10.0
1,2,1,5,42,2022-11-02,15.0
2,3,1,10,18,2022-09-30,8.0
3,4,1,15,5,2022-10-20,10.0
4,5,1,20,12,NaN,15.0

In [72]:
customers.head()

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,California,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,NaN
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12

# 2. Exploratory Analysis

## * Obtain summary statistics for numerical columns

In [6]:
sales.describe()

         sale_id   store_id  customer_id  product_id   quantity        total
count  40.000000  39.000000    40.000000   40.000000  40.000000    40.000000
mean   20.500000   6.487179    14.075000   13.500000   1.625000   352.296500
std    11.690452   4.235637     8.303189    8.857852   0.952392   377.625776
min     1.000000   1.000000     1.000000    1.000000   1.000000    19.980000
25%    10.750000   3.000000     6.750000    5.750000   1.000000    99.737500
50%    20.500000   6.000000    13.500000   11.500000   1.000000   229.985000
75%    30.250000   9.500000    20.250000   21.250000   2.000000   352.487500
max    40.000000  15.000000    29.000000   30.000000   5.000000  1599.990000

In [9]:
products.describe()

       product_id        price         cost     weight
count   30.000000    30.000000    30.000000  28.000000
mean    15.500000   191.724000   203.159000   3.835714
std      8.803408   452.483576   278.924138   5.693236
min      1.000000 -1599.990000     1.800000   0.200000
25%      8.250000    46.990000    28.375000   0.500000
50%     15.500000   134.990000    82.500000   1.150000
75%     22.750000   322.490000   236.250000   3.750000
max     30.000000  1299.990000  1100.000000  25.000000

In [66]:
inventory.describe()

       inventory_id   store_id  product_id  quantity_in_stock  reorder_level
count     75.000000  75.000000   75.000000          75.000000      69.000000
mean      38.000000   8.000000   12.733333          22.640000      12.681159
std       21.794495   4.349588    7.179801          13.923187       3.327659
min        1.000000   1.000000    1.000000           0.000000       8.000000
25%       19.500000   4.000000    6.500000          15.000000      10.000000
50%       38.000000   8.000000   13.000000          25.000000      10.000000
75%       56.500000  12.000000   19.000000          33.500000      15.000000
max       75.000000  15.000000   25.000000          45.000000      20.000000

## * Check for missing values in all dataframes

In [5]:
print('\nStores: Columns/Missing values')
stores.isnull().sum()

Stores: Columns/Missing values

store_id        0
store_name      0
address         0
city            0
state           0
zip_code        0
region          0
size_sqft       2
opening_date    1
dtype: int64

In [6]:
print('\nSales: Columns/Missing values')
sales.isnull().sum()

Sales: Columns/Missing values

sale_id           0
date              1
store_id          1
customer_id       0
product_id        0
quantity          0
total             0
payment_method    1
dtype: int64

In [7]:
print('\nProducts: Columns/Missing values')
products.isnull().sum()

Products: Columns/Missing values

product_id      0
product_name    0
category        0
subcategory     0
brand           0
price           0
cost            0
weight          2
dtype: int64

In [8]:
print('\nInventory: Columns/Missing values')
inventory.isnull().sum()

Inventory: Columns/Missing values

inventory_id         0
store_id             0
product_id           0
quantity_in_stock    0
last_restock_date    9
reorder_level        6
dtype: int64

In [9]:
print('\nCustomers: Columns/Missing values')
customers.isnull().sum()

Customers: Columns/Missing values

customer_id          0
first_name           0
last_name            0
email                3
phone                2
address              0
city                 0
state                0
zip_code             1
registration_date    3
dtype: int64

## * Display the data types of each column

In [10]:
print('\nStores: Columns/Data Types')
stores.dtypes

Stores: Columns/Data Types

store_id          int64
store_name          str
address             str
city                str
state               str
zip_code            str
region              str
size_sqft       float64
opening_date        str
dtype: object

In [11]:
print('\nSales: Columns/Data Types')
sales.dtypes

Sales: Columns/Data Types

sale_id             int64
date                  str
store_id          float64
customer_id         int64
product_id          int64
quantity            int64
total             float64
payment_method        str
dtype: object

In [12]:
print('\nProducts: Columns/Data Types')
products.dtypes

Products: Columns/Data Types

product_id        int64
product_name        str
category            str
subcategory         str
brand               str
price           float64
cost            float64
weight          float64
dtype: object

In [13]:
print('\nInventory: Columns/Data Types')
inventory.dtypes

Inventory: Columns/Data Types

inventory_id           int64
store_id               int64
product_id             int64
quantity_in_stock      int64
last_restock_date        str
reorder_level        float64
dtype: object

In [14]:
print('\nCustomers: Columns/Data Types')
customers.dtypes

Customers: Columns/Data Types

customer_id          int64
first_name             str
last_name              str
email                  str
phone                  str
address                str
city                   str
state                  str
zip_code               str
registration_date      str
dtype: object

# 3. Basic Information Retrieval

## * How many unique products are in the product catalog?

In [17]:
dupe_prods = products.duplicated(subset=['product_name']).sum()

print('\n=========================================================================')
print(f'The number of duplicate products in the product table is {dupe_prods}.')
print('=========================================================================\n')

=========================================================================
The number of duplicate products in the product table is 0.
=========================================================================

## * What are the top 5 most expensive products?

In [18]:
top_5 = products.nlargest(5, 'price')[['product_name', 'price']]

print('\n=======================================================')
print("The top 5 most expensive products are:")
print()
for i, row in enumerate(top_5.itertuples(), start=1):
    print(f"{i}) {row.product_name:<25} ${row.price:,.2f}")
print('=======================================================\n')

=======================================================
The top 5 most expensive products are:

1) Dell XPS 13               $1,299.99
2) Apple iPhone 13           $899.99
3) Samsung Galaxy S21        $799.99
4) Dyson V11 Vacuum          $599.99
5) Sony PlayStation 5        $499.99
=======================================================

## * Which store has the largest floor space?

In [19]:
# 1st try

biggest = stores.nlargest(1,'size_sqft')[['store_name', 'size_sqft']]

print('\n====================================================================================')
for y in biggest.itertuples():
    print(f"The {y.store_name} has the largest floor space with {y.size_sqft:,} sq feet.")
print('====================================================================================\n')

====================================================================================
The Los Angeles Plaza has the largest floor space with 55,000.0 sq feet.
====================================================================================

In [21]:
# 2nd try
row = stores.nlargest(1, 'size_sqft').iloc[0]

print('\n====================================================================================')
print(f"The {row.store_name} has the largest floor space with {row.size_sqft:,} sq feet.")
print('====================================================================================\n')

====================================================================================
The Los Angeles Plaza has the largest floor space with 55,000.0 sq feet.
====================================================================================

## * What is the distribution of customers by state?

In [165]:
state_abbrev = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR',
    'California': 'CA', 'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE',
    'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 'Idaho': 'ID',
    'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS',
    'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD',
    'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS',
    'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV',
    'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM', 'New York': 'NY',
    'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK',
    'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC',
    'South Dakota': 'SD', 'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT',
    'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV',
    'Wisconsin': 'WI', 'Wyoming': 'WY'
}
customers['state'] = customers['state'].map(state_abbrev).fillna(customers['state'])
customers['state'].value_counts()

state
TX    5
CA    4
NY    2
MD    2
IL    1
AZ    1
PA    1
FL    1
OH    1
NC    1
IN    1
WA    1
CO    1
MA    1
OR    1
NV    1
MI    1
TN    1
KY    1
WI    1
NM    1
MO    1
Name: count, dtype: int64

# 4. Data Cleaning - Handling Missing Values

## * Create copies of original DataFrames for cleaning

In [171]:
inventory_raw = inventory.copy()
inventory_raw.head()

,inventory_id,store_id,product_id,quantity_in_stock,last_restock_date,reorder_level
0,1,1,1,25,2022-10-15,10.0
1,2,1,5,42,2022-11-02,15.0
2,3,1,10,18,2022-09-30,8.0
3,4,1,15,5,2022-10-20,10.0
4,5,1,20,12,NaN,15.0

In [170]:
stores_raw = stores.copy()
stores_raw.head()

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
0,1,City Center,123 Retail Blvd,New York,NY,10001,Northeast,32500.0,2005-05-20
1,2,Mall of Chicago,456 Shopping Ave,Chicago,IL,60611,Midwest,45000.0,2007-08-15
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10
3,4,Houston Galleria,321 Main St,Houston,Texas,77002,Southwest,NaN,2008-11-05
4,5,Phoenix Outlet,654 Desert Rd,Phoenix,AZ,85001,Southwest,18500.0,2010-06-30

In [172]:
sales_raw = sales.copy()
sales_raw.head()

,sale_id,date,store_id,customer_id,product_id,quantity,total,payment_method
0,1,2022-01-15,3.0,12,5,2,49.98,Credit Card
1,2,2022-01-16,1.0,5,10,1,49.99,credit card
2,3,2022-01-18,2.0,8,3,1,349.99,DEBIT CARD
3,4,2022-01-20,4.0,20,7,1,349.99,Cash
4,5,2022-01-22,5.0,3,15,1,1599.99,CC

In [173]:
products_raw = products.copy()
products_raw.head()

,product_id,product_name,category,subcategory,brand,price,cost,weight
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
2,3,Sony WH-1000XM4,ELECTRONICS,Headphones,Sony,349.99,210.00,0.60
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
4,5,Nike Classic Tee,Clothing,Shirts,Nike,24.99,12.50,0.20

In [174]:
customers_raw = customers.copy()
customers_raw.head()

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,CA,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,NaN
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12

## * Identify all missing values in each dataset

In [22]:
stores.isnull().sum()

store_id        0
store_name      0
address         0
city            0
state           0
zip_code        0
region          0
size_sqft       2
opening_date    1
dtype: int64

In [23]:
sales.isnull().sum()

sale_id           0
date              1
store_id          1
customer_id       0
product_id        0
quantity          0
total             0
payment_method    1
dtype: int64

In [24]:
customers.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                3
phone                2
address              0
city                 0
state                0
zip_code             1
registration_date    3
dtype: int64

In [25]:
inventory.isnull().sum()

inventory_id         0
store_id             0
product_id           0
quantity_in_stock    0
last_restock_date    9
reorder_level        6
dtype: int64

In [26]:
products.isnull().sum()

product_id      0
product_name    0
category        0
subcategory     0
brand           0
price           0
cost            0
weight          2
dtype: int64

## * For numerical columns with missing values, replace with column mean

In [25]:
stores['size_sqft'].fillna(stores['size_sqft'].mean())

0     32500.000000
1     45000.000000
2     55000.000000
3     30653.846154
4     18500.000000
5     22000.000000
6     35000.000000
7     27500.000000
8     42000.000000
9     16500.000000
10    29000.000000
11    31500.000000
12    24000.000000
13    30653.846154
14    20000.000000
Name: size_sqft, dtype: float64

In [27]:
inventory['reorder_level'].fillna(inventory['reorder_level'].mean())

0     10.0
1     15.0
2      8.0
3     10.0
4     15.0
      ...
70    10.0
71     8.0
72    10.0
73    15.0
74    10.0
Name: reorder_level, Length: 75, dtype: float64

In [28]:
products['weight'].fillna(products['weight'].mean())

0      0.450000
1      0.500000
2      0.600000
3      2.800000
4      0.200000
5      0.900000
6     10.000000
7      3.500000
8      3.835714
9      2.000000
10     1.300000
11     0.700000
12     1.500000
13     0.300000
14     3.500000
15     0.500000
16     1.000000
17     0.600000
18     0.400000
19     6.700000
20    25.000000
21     3.835714
22     8.500000
23    12.000000
24     0.350000
25     0.900000
26     4.500000
27    15.000000
28     0.500000
29     3.200000
Name: weight, dtype: float64

## *For categorical columns with missing values, replace with most frequent value

In [111]:
sales.isna().sum()
sales.head()
sales['payment_method'].mode()[0]
sales['payment_method'].fillna(sales['payment_method'].mode()[0])

0     Credit Card
1     credit card
2      DEBIT CARD
3            Cash
4              CC
5            Visa
6          PayPal
7       Apple Pay
8           Debit
9            Cash
10    Credit Card
11             DC
12           cash
13    Credit Card
14     Debit Card
15         paypal
16       ApplePay
17           Cash
18    Credit Card
19    CREDIT CARD
20     Debit Card
21             PP
22           Cash
23         Credit
24      GooglePay
25    Credit Card
26     debit card
27           Cash
28         PayPal
29     Debit Card
30    Credit Card
31           Cash
32    Credit Card
33     Debit Card
34    Credit Card
35           Cash
36         PayPal
37     google pay
38    Credit Card
39           CASH
Name: payment_method, dtype: str

## *For date columns with missing values, use forward fill or backward fill as appropriate

In [132]:
stores.isna().sum()
stores
stores['opening_date']
stores['opening_date'].ffill()

0     2005-05-20
1     2007-08-15
2     2004-03-10
3     2008-11-05
4     2010-06-30
5     2009-09-12
6     2012-04-22
7     2006-07-18
8     2006-07-18
9     2014-10-09
10    2011-02-14
11    2015-08-27
12    2016-12-03
13    2013-05-11
14    2018-09-25
Name: opening_date, dtype: str

In [137]:
sales.isna().sum()
sales['date']
sales['date'].ffill()

0     2022-01-15
1     2022-01-16
2     2022-01-18
3     2022-01-20
4     2022-01-22
5     2022-02-01
6     2022-02-03
7     2022-02-05
8     2022-02-08
9     2022-02-10
10    2022-02-15
11    2022-02-19
12    2022-02-22
13    2022-03-01
14    2022-03-05
15    2022-03-10
16    2022-03-15
17    2022-03-20
18    2022-03-25
19    2022-04-01
20    2022-04-05
21    2022-04-10
22    2022-04-15
23    2022-04-20
24    2022-04-25
25    2022-05-01
26    2022-05-05
27    2022-05-10
28    2022-05-15
29    2022-05-20
30    2022-05-20
31    2022-06-01
32    2022-06-05
33    2022-06-10
34    2022-06-15
35    2022-06-20
36    2022-06-25
37    2022-07-01
38    2022-07-05
39    2022-07-10
Name: date, dtype: str

In [140]:
customers.isnull().sum()
customers['registration_date']
customers['registration_date'].ffill()

0     2021-03-15
1     2020-11-02
2     2021-05-20
3     2021-05-20
4     2020-09-12
5     2021-02-28
6     2021-01-17
7     2020-10-05
8     2021-06-30
9     2020-08-22
10    2021-04-09
11    2020-12-27
12    2021-07-14
13    2020-07-18
14    2021-01-03
15    2021-01-03
16    2020-10-19
17    2021-03-01
18    2020-09-05
19    2021-05-12
20    2020-11-30
21    2021-02-14
22    2020-08-08
23    2021-04-25
24    2021-04-25
25    2020-07-01
26    2020-07-01
27    2021-06-17
28    2020-09-30
29    2021-01-28
30    2020-10-15
Name: registration_date, dtype: str

In [157]:
inventory.head()
inventory.isnull().sum()
inventory['last_restock_date']
# inven = inventory['last_restock_date'].ffill()
# inven.tolist()
inventory['last_restock_date'].ffill()

0     2022-10-15
1     2022-11-02
2     2022-09-30
3     2022-10-20
4     2022-10-20
         ...
70    2022-10-16
71    2022-09-25
72    2022-11-22
73    2022-10-01
74    2022-10-01
Name: last_restock_date, Length: 75, dtype: str

# 5. Removing Duplicates

## * Check for and remove any duplicate entries in the customers and products dataframes

In [178]:
# cheack for duplicate customer records by customer_id
customers.duplicated().sum()
customers['customer_id'].duplicated().sum()
customers['customer_id'].duplicated()
customers[customers['customer_id'].duplicated(keep=False)]

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
25,26,Betty,Lewis,betty.lewis@gmail.com,5551597532,753 MacArthur Blvd,Baltimore,Maryland,21202,2020-07-01
26,26,Betty,Lewis,blewis23@gmail.com,555 159 7532,753 MacArthur Boulevard,Baltimore,MD,21202,2020-07-01

In [182]:
customers[customers['customer_id'].duplicated(keep=False)]

# Keeps most recent entry for customer

customers.drop_duplicates(subset='customer_id', keep='last')

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,California,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,NaN
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12
5,6,Jennifer,Miller,jmiller@outlook.com,NaN,898 Cedar Dr,Phoenix,AZ,85001,2021-02-28
6,7,Michael,Davis,mdavis@gmail.com,555.432.7654,742 Maple Ave,Philadelphia,PA,19103,2021-01-17
7,8,Linda,Garcia,lgarcia@yahoo.com,555 876 2345,953 Oak Ln,San Antonio,Texas,78205,2020-10-05
8,9,William,Rodriguez,wrodriguez@hotmail.com,5558889999,159 Washington Blvd,San Diego,CA,92101,2021-06-30
9,10,Elizabeth,Wilson,ewilson@gmail.com,(555) 333-2211,753 Lincoln Rd,Dallas,TX,75201,2020-08-22
10,11,David,Martinez,dmartinez@yahoo.com,555-111-3333,246 Jefferson Ave,San Jose,CA,95113,2021-04-09
11,12,Barbara,Anderson,NaN,555.444.9876,135 Madison St,Austin,TX,NaN,2020-12-27
12,13,Richard,Taylor,rtaylor@outlook.com,5552223333,864 Adams Ct,Jacksonville,FL,32202,2021-07-14
13,14,Susan,Thomas,sthomas45@gmail.com,NaN,579 Monroe Pl,Fort Worth,TX,76102,2020-07-18
14,15,Joseph,Hernandez,jhernandez@yahoo.com,555-777-8888,951 Jackson Dr,Columbus,OH,43215,2021-01-03
15,16,Jessica,Moore,jmoore@hotmail.com,555.666.1234,357 Tyler St,Charlotte,North Carolina,28202,NaN
16,17,Thomas,Martin,tmartin@gmail.com,(555) 444-5678,159 Polk Ave,San Francisco,CA,94102,2020-10-19
17,18,Sarah,Jackson,sjackson@yahoo.com,5557890123,753 Harrison Rd,Indianapolis,IN,46204,2021-03-01
18,19,Charles,Thompson,cthompson@outlook.com,555-321-6547,951 Van Buren St,Seattle,Washington,98101,2020-09-05
19,20,Karen,White,kwhite88@gmail.com,555.789.4561,357 Fillmore Dr,Denver,CO,80202,2021-05-12
20,21,Christopher,Lopez,clopez@yahoo.com,555 456 7890,159 Pierce Ave,Boston,MA,02108,2020-11-30
21,22,Nancy,Lee,nlee@hotmail.com,5559876543,753 Hayes Blvd,Portland,Oregon,97201,2021-02-14
22,23,Daniel,Gonzalez,dgonzalez@gmail.com,(555) 123-7890,951 Grant St,Las Vegas,NV,89101,2020-08-08
23,24,Margaret,Harris,mharris@yahoo.com,555-321-6789,357 Sherman Rd,Detroit,MI,48226,2021-04-25
24,25,Matthew,Clark,mclark@outlook.com,555.654.9870,159 Sheridan Dr,Nashville,TN,37201,NaN
26,26,Betty,Lewis,blewis23@gmail.com,555 159 7532,753 MacArthur Boulevard,Baltimore,MD,21202,2020-07-01
27,27,Steven,Robinson,srobinson@yahoo.com,555-951-7532,951 Hooker St,Louisville,KY,40202,2021-06-17
28,28,Dorothy,Walker,dwalker@hotmail.com,5553579514,357 Halsted Ave,Milwaukee,WI,53202,2020-09-30
29,29,Anthony,Perez,NaN,555.753.9512,159 Ashland Dr,Albuquerque,NM,87102,2021-01-28
30,30,Lisa,Hall,lhall@gmail.com,(555) 951-7530,753 Morgan St,Kansas City,MO,64101,2020-10-15

In [196]:
# Checked product_id and product name, and show no duplicate rows for same product

products.head()
products.sort_values('product_name')

products.duplicated().sum()
products['product_name'].duplicated().sum()
products['product_id'].duplicated().sum()

np.int64(0)

# Discussion Questions

### 1. What are the key advantages of using Pandas for data cleaning compared to other methods?

#####        * Pandas has many built in functions that allow for summary viewing instead of line-by-line

### 2. How would your approach to handling missing values differ if the missing data was not random but had a pattern or meaning?

#####        * Would assign a value based on the data i was dealing with or keep as null if null values had meaning.

### 3. What types of data quality issues might not be immediately visible through simple DataFrame inspection methods?

#####        *formatting (upper or lowercase)
#####        *If there ar 0 valeues in rows that need to be divided by

### 4. How would you document your data cleaning process to ensure reproducibility?

#####        * show function used and what i am trying to analyze

### 5. In what scenarios might it be better to remove rows with missing values rather than imputing them?

#####        * When dealing with a large dataset where 1 record does not affect the analysis
#####        * 0 values in rows that need to use for calulations (divide by 0)