# Week 9 Workshop: Advanced Pandas Retail Chain Performance Analysis

## Background
##### You're working as a data analyst for a retail chain that wants to better understand their sales patterns and customer behavior. The company has collected data on customers, products, and sales transactions. Your task is to use Pandas techniques including DateTime analysis and data aggregation to provide basic insights for the business team.

## Workshop Tasks

### Part 1: DateTime Operations

#### 1. Converting and Working with Dates:

#### * Load all three CSV files and convert date columns to proper DateTime format using pd.to_datetime()

In [1]:
# import pandas and numpy
import pandas as pd
import numpy as np

In [16]:
# Load csv files

customers = pd.read_csv('customers_wk9_thurs.csv')
products = pd.read_csv('products_wk9_thurs.csv')
sales = pd.read_csv('sales_wk9_thurs.csv')

print(f"\nThe customers file has {len(customers)} rows.")
print(f"\nThe products file has {len(products)} rows.")
print(f"\nThe sales file has {len(sales)} rows.\n")

The customers file has 100 rows.

The products file has 60 rows.

The sales file has 150 rows.

#### * Customers table: Converting date formats

In [66]:
# review customers columns/formats
print("\n* Find the date fields below:\n")
customers.info()

# review date field formats
print("\n* Review date formats for date fields:\n")
print(customers['registration_date'].head()) # yyyy-mm-dd

# review code
print('\n* The variable created to change date shows:\n')
cust_reg_date = pd.to_datetime(customers['registration_date'])
print(cust_reg_date[0:5])

# commit registration date code
customers['registration_date'] = cust_reg_date

# validate results
print("\n* The updated date format should be datetime:\n")
customers['registration_date'].info()

* Find the date fields below:

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        100 non-null    int64
 1   first_name         100 non-null    str
 2   last_name          100 non-null    str
 3   age                100 non-null    int64
 4   state              100 non-null    str
 5   income             100 non-null    int64
 6   registration_date  100 non-null    datetime64[us]
 7   email              100 non-null    str
dtypes: datetime64[us](1), int64(3), str(4)
memory usage: 6.4 KB

* Review date formats for date fields:

0   2022-01-15
1   2022-01-22
2   2022-02-03
3   2022-02-14
4   2022-02-28
Name: registration_date, dtype: datetime64[us]

* The variable created to change date shows:

0   2022-01-15
1   2022-01-22
2   2022-02-03
3   2022-02-14
4   2022-02-28
Name: registration_date, dtype: datetime64[us]

* The updated date format should be datetime:

<class 'pandas.Series'>
RangeIndex: 100 entries, 0 to 99
Series name: registration_date
Non-Null Count  Dtype
--------------  -----
100 non-null    datetime64[us]
dtypes: datetime64[us](1)
memory usage: 932.0 bytes

##### Sales table: Converting date formats

In [65]:
# review sales columns/formats
print("\n* Find the date fields below:\n")
sales.info()

# review date field formats
print("\n* Review date formats for date fields:\n")
print(sales['transaction_date'].head()) # yyyy-mm-dd

# review code
print('\n* The variable created to change date shows:\n')
sales_trans_date = pd.to_datetime(sales['transaction_date'])
print(sales_trans_date[0:5])

# commit registration date code
sales['transaction_date'] = sales_trans_date

# validate results
print("\n* The updated date format should be datetime:\n")
sales['transaction_date'].info()

* Find the date fields below:

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sale_id           150 non-null    int64
 1   customer_id       150 non-null    int64
 2   product_id        150 non-null    int64
 3   transaction_date  150 non-null    datetime64[us]
 4   quantity          150 non-null    int64
 5   total_amount      150 non-null    float64
dtypes: datetime64[us](1), float64(1), int64(4)
memory usage: 7.2 KB

* Review date formats for date fields:

0   2022-02-10 14:30:00
1   2022-02-15 10:15:00
2   2022-02-20 16:45:00
3   2022-02-25 11:20:00
4   2022-03-01 13:10:00
Name: transaction_date, dtype: datetime64[us]

* The variable created to change date shows:

0   2022-02-10 14:30:00
1   2022-02-15 10:15:00
2   2022-02-20 16:45:00
3   2022-02-25 11:20:00
4   2022-03-01 13:10:00
Name: transaction_date, dtype: datetime64[us]

* The updated date format should be datetime:

<class 'pandas.Series'>
RangeIndex: 150 entries, 0 to 149
Series name: transaction_date
Non-Null Count  Dtype
--------------  -----
150 non-null    datetime64[us]
dtypes: datetime64[us](1)
memory usage: 1.3 KB

In [67]:
# review sales columns/formats
print("\n* Find the date fields below:\n")
products.info()

# review date field formats
print("\n* Review date formats for date fields:\n")
print(products['launch_date'].head()) 

# review code
print('\n* The variable created to change date shows:\n')
prod_launch_date = pd.to_datetime(products['launch_date'])
print(prod_launch_date[0:5])

# commit registration date code
products['launch_date'] = prod_launch_date

# validate results
print("\n* The updated date format should be datetime:\n")
products['launch_date'].info()

* Find the date fields below:

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    60 non-null     int64
 1   product_name  60 non-null     str
 2   category      60 non-null     str
 3   price         60 non-null     float64
 4   launch_date   60 non-null     str
 5   brand         60 non-null     str
dtypes: float64(1), int64(1), str(4)
memory usage: 2.9 KB

* Review date formats for date fields:

0    2021-03-15
1    2021-04-20
2    2021-05-10
3    2021-06-01
4    2021-06-15
Name: launch_date, dtype: str

* The variable created to change date shows:

0   2021-03-15
1   2021-04-20
2   2021-05-10
3   2021-06-01
4   2021-06-15
Name: launch_date, dtype: datetime64[us]

* The updated date format should be datetime:

<class 'pandas.Series'>
RangeIndex: 60 entries, 0 to 59
Series name: launch_date
Non-Null Count  Dtype
--------------  -----
60 non-null     datetime64[us]
dtypes: datetime64[us](1)
memory usage: 612.0 bytes

#### * Extract useful components from the sales transaction dates: year, month, and day of week

In [108]:
print('\nThe full datetime:\n')
print(sales['transaction_date'].head())

print('\n* The extracted years:\n')
print(sales['transaction_date'].dt.year[0:5])

print('\n* The extracted month numbers:\n')
print(sales['transaction_date'].dt.month[0:5])

print('\n* The extracted month names:\n')
print(sales['transaction_date'].dt.month_name()[0:5])

print('\n* The extracted month abbreviations:\n')
print(sales['transaction_date'].dt.strftime('%b')[0:5])

print('\n* The extracted date numbers:\n')
print(sales['transaction_date'].dt.day[0:5])

print('\n* The extracted day numbers of week:\n')
print(sales['transaction_date'].dt.day_of_week[0:5])

print('\n* The extracted day names of week:\n')
print(sales['transaction_date'].dt.day_name()[0:5])

The full datetime:

0   2022-02-10 14:30:00
1   2022-02-15 10:15:00
2   2022-02-20 16:45:00
3   2022-02-25 11:20:00
4   2022-03-01 13:10:00
Name: transaction_date, dtype: datetime64[us]

* The extracted years:

0    2022
1    2022
2    2022
3    2022
4    2022
Name: transaction_date, dtype: int32

* The extracted month numbers:

0    2
1    2
2    2
3    2
4    3
Name: transaction_date, dtype: int32

* The extracted month names:

0    February
1    February
2    February
3    February
4       March
Name: transaction_date, dtype: str

* The extracted month abbreviations:

0    Feb
1    Feb
2    Feb
3    Feb
4    Mar
Name: transaction_date, dtype: str

* The extracted date numbers:

0    10
1    15
2    20
3    25
4     1
Name: transaction_date, dtype: int32

* The extracted day numbers of week:

0    3
1    1
2    6
3    4
4    1
Name: transaction_date, dtype: int32

* The extracted day names of week:

0    Thursday
1     Tuesday
2      Sunday
3      Friday
4     Tuesday
Name: transaction_date, dtype: str

#### * Display the date range covered by your sales data (earliest and latest dates)

In [133]:
min_trans_date = sales['transaction_date'].min().date()
max_trans_date = sales['transaction_date'].max().date()

print(f'\nThe sales transaction dates range between {min_trans_date} and {max_trans_date}.\n')

The sales transaction dates range between 2022-02-10 and 2024-03-05.

### 2. Basic Time Analysis:

#### Find the busiest day of the week for sales (by counting transactions)

In [182]:
dow = sales['transaction_date'].dt.day_name().rename('weekday')

top = sales.groupby(dow)['sale_id'].count().sort_values(ascending=False)

print(f'\nAs the chart below illustrates, the best day for sales is {top.index[0]} with {top.iloc[0]}.\n')

sales.groupby(dow).agg(num_sales = ('sale_id', 'count')).sort_values('num_sales', ascending=False)

As the chart below illustrates, the best day for sales is Friday with 24.

           num_sales
weekday
Friday            24
Tuesday           22
Saturday          21
Thursday          21
Sunday            21
Wednesday         21
Monday            20

#### Determine which month had the most transactions

In [183]:
month_name = sales['transaction_date'].dt.month_name().rename('month_name')

top_mo = sales.groupby(month_name)['sale_id'].count().sort_values(ascending=False)

print(f'\nAs the chart below illustrates, the best month for sales is {top_mo.index[0]} with {top_mo.iloc[0]}.\n')

sales.groupby(month_name).agg(num_sales = ('sale_id', 'count')).sort_values('num_sales', ascending=False)

As the chart below illustrates, the best month for sales is February with 16.

            num_sales
month_name
February           16
December           14
March              14
August             12
April              12
July               12
June               12
May                12
October            12
November           12
September          12
January            10

#### Count how many sales happened in each year

In [194]:
year_num = sales['transaction_date'].dt.year.rename('year')

sales.groupby(year_num).agg(num_sales = ('sale_id', 'count')).sort_values('num_sales', ascending=False)

      num_sales
year
2023         72
2022         65
2024         13

### Part 2: GroupBy and Aggregation

#### 1. Product Analysis:

#### * Group products by category and calculate the average price for each category

In [216]:
products.groupby('category').agg(
        total_price = ('price', 'mean')).sort_values('total_price', ascending=False).round(2)

                   total_price
category
Sports & Outdoors       105.90
Electronics              59.99
Clothing                 52.24
Accessories              35.07
Home & Garden            30.16

#### * Count how many products are in each category

In [222]:
products.groupby('category').agg(
        total_prods = ('product_id', 'count')).sort_values('total_prods', ascending=False)

                   total_prods
category
Electronics                 13
Accessories                 12
Clothing                    12
Home & Garden               12
Sports & Outdoors           11

#### 2. Customer Analysis

#### * Group customers by state and find the average age in each state

In [230]:
customers.groupby('state').agg(
    avg_age = ('age','mean')).sort_values('state')

       avg_age
state
CA       34.10
FL       39.00
IL       37.25
NY       36.50
TX       38.30

#### * Calculate total spending per customer (sum up all their purchases)

In [233]:
sales.groupby('customer_id').agg(
        sum_purch = ('total_amount', 'sum')).iloc[0:10]

             tot_purch
customer_id
1               229.98
2               179.96
3               154.98
4               234.95
5               149.98
6               219.96
7               169.98
8               174.96
9               139.96
10               94.98

#### * Find customers who have made the most purchases

In [240]:
sales.groupby('customer_id').agg(
        tot_purch = ('quantity', 'sum')).sort_values('tot_purch', ascending=False).iloc[0:9]

             tot_purch
customer_id
40                   8
55                   7
60                   7
52                   7
28                   6
58                   6
23                   6
20                   5
15                   5

#### 3. Sales Analysis:

#### * Calculate total sales revenue by month

In [251]:
rev_mo = sales['transaction_date'].dt.to_period('M').rename('month')

sales.groupby(rev_mo).agg(total_revenue=('total_amount', 'sum'))

         total_revenue
month
2022-02         229.93
2022-03         504.92
2022-04         415.90
2022-05         450.90
2022-06         502.84
2022-07         485.90
2022-08         376.87
2022-09         660.90
2022-10         493.90
2022-11         481.89
2022-12         730.85
2023-01         384.91
2023-02         750.87
2023-03         440.90
2023-04         508.87
2023-05         726.89
2023-06         483.84
2023-07         444.90
2023-08         493.87
2023-09         489.86
2023-10         741.90
2023-11         540.87
2023-12         727.86
2024-01         479.88
2024-02         688.86
2024-03         169.95

#### * Find the average transaction amount by day of the week

In [257]:
dow1 = sales['transaction_date'].dt.day_of_week.rename('day_of_wk')
sales.groupby(dow1).agg(avg_amount=('total_amount', 'mean')).round(2)

           avg_amount
day_of_wk
0               90.93
1               74.03
2               96.07
3              102.27
4              100.94
5               61.12
6               99.55

#### * Determine which product category generates the most total revenue

In [268]:
prod_sales =pd. merge(sales[['product_id','total_amount']], products[['product_id','category']], on ='product_id')
prod_sales.groupby('category').agg(tot_rev=('total_amount','sum')).sort_values('tot_rev', ascending=False)

                   tot_rev
category
Sports & Outdoors  3544.64
Electronics        3524.29
Clothing           2745.39
Accessories        2053.25
Home & Garden      1541.46

#### Part 3: Basic Data Insights

#### * Find which state has the most customers

In [269]:
customers.groupby('state').agg(tot_custs=('customer_id', 'count'))

       tot_custs
state
CA            20
FL            20
IL            20
NY            20
TX            20

#### * Identify the top 5 customers by total spending

In [274]:
sales.groupby('customer_id').agg(tot_spend=('total_amount','sum')).sort_values('tot_spend', ascending=False).iloc[0:5]

             tot_spend
customer_id
31              379.97
13              359.96
41              329.98
84              319.98
30              284.98

#### * Determine which day of the week has the highest average transaction value

In [281]:
dow2 = sales['transaction_date'].dt.day_name().rename('day_of_wk')
sales.groupby(dow2).agg(avg_amount=('total_amount', 'mean')).round(2).sort_values('avg_amount', ascending=False)

           avg_amount
day_of_wk
Thursday       102.27
Friday         100.94
Sunday          99.55
Wednesday       96.07
Monday          90.93
Tuesday         74.03
Saturday        61.12

## Discussion Questions

### 1. DateTime Benefits: How can extracting day of the week and month from dates help a retail business make better decisions?

##### Based on days, weeks, or months businesses can:
#####    (a) Allocate resources staffing, inventory etc. based on time periods
#####    (b) Run sales on certain products on slow sales periods

### 2. GroupBy Value: Why is it useful to group data by categories, states, or time periods rather than looking at individual transactions?

##### By grouping you see higher level trends by categories that individual transactions will no tell you.

### 3. Business Applications: Based on your findings, what simple recommendations would you give to help the retail chain improve their performance?

##### (a) Run promotions on slow days like tuesday, saturday, and monday
##### (b) Increase inventory for sports & Outdoor equipment and Electronics